################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonar.klauke-enterprises.com -Dsonar.projectKey=portum -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - secure: fivUa2dCWkeOFp2IoMfPXgKFrlkyTVDYNpLEqsZ9XqyXurrrXXdSr5l9kL8S1HIlnb1X3YKM481r+jbRgo8ugdIcE3D2TygJ5e93rFdzIxDGEokuScOs6YadhfX3uTuMrH5ly60dj8/QCs9wBJvNZGx6vxEE+V9FPby2x8zDULAV3+fQUugqcqEaov8mTrRVqmk3Qv08026NTHKxix7EaAcCRkZhLvGM8LfEDGRGuoZFdkrlkGuqlLQbbO/FwyWlW+C7to8pTe+unSsik9jOKHwMc2kY1u22ShZvSZD0/YD7gGOn1Z80dFVvJ8hwtgOaAWtzCR9xYSfeeirUzPI6A+ErweJocqfco2RabpUtNH9L4zes4nPfhvFNLKzh28Qpch6wbJWpRqP/mNRL7W9JezV2yN5gQt/kZ1Fs0um9FFdzW22CITeBqD8BnJ34wDuuWTuWCfsm9JhArnxtjHUiTzTnC15oXlPMgYT5Fl5aLBWxTZnvG7+b8jzx1zxwoSikA7dMAU5hNTermEVY4mCairZgi1BxamPHhf95j+oteqd6l1xQ/b0oT1z9C91ecT9Bkdc1riEFuOtZe1v66kTjrQhEuNISDdekfB4vnK4xM8CczHceGh6NxDgZhZPW3fZLercJc2KRLq3UsyYLS1pftYXJUrp/eUT1WTjnWr9mM48=
    - secure: l+zM2wrR1Q/kMQoSUhK0WeeZnk2yvJEwqs3taWaOKDJOEay8VzEl1X4LJgHi0ymKThIjLCOrQQY+orB7kMi3ThZlOGTQ7cAPa3+gUCS4yAlhoQrQdTQ1dnSMM36ju0QOTOksSt0ZqVAA3ULIH7DHnbGnss5iHAuiQYgSTDDCa7MPi1YdnqXoN+pGGDu2CF4N6PqHKvPhd6J8O/bsM/9YJ7FCd/yySf5896OF6w5XO3xKuxC7Ib0D6VngtHr+v+1erkwtlhbwqUISn8Ww8KoVwiHU3GBAgpKS0JhNJ9YcUkuHiAUKvvrWL81svWplE07OWytD+KJxqr1VS0NJJVEWi6CYAcngplvLDLXx3qBi8WFZRl2aMBKmUXP/SgV+uTsQ3LCUE+LAj7Zxu51EK31cgiKpjyGxL7fbHOZz9PT5zv8SGpBJzlA7ZIpbwybmCGMmDmEyjV6F9TiSCVI0TdKEBkYFVPTj1ltq2qjwqP7skhp8KV1wirdL7y2hP7ewAG3Qj64d95Y2gYL0AoUDQcc+D62DDiIiBaccJxcvyxWylDlwT0xA+rPC9CuSO+y2+7da/+jaKGYIB6D4lk2dZRk7sCzdifZg3JuzJVBJeAYzPjyAsfH5esHk1inuyjLM2VFbmzqiJ3H253MLjMrotLzoSg7PzLxnMWmKLmhKT9N8UK4=
    - secure: QCfcUSOmGSYwSXeEavib1Y1gYoqubdcAWMLsbdIL77sRo6AjnTetdNxZkvt2QAvmzN2j80NeFI5C2hIwQkjTdlU6P2w1ir2OGBl5kWOEKxpTiPGkHOrRy0f7U7zpdbEOPbYK8+td7nVcd2RvhPGCcUfi2rRA6KtThNw8CvAbBq8YgW2cmvh2z6eVE/l/jP0m3hfebv7p/Sw3Xzm27EijSMg+QmFFXhkfGgnco2Mux5gwIpBds+q/ILiSL0/2X+jSKJvHzX+LWIoYwXpq2gUXd33zlrK99WvJmbRXDCZqymTrNE8ZLVazINin/cOFK4jhcEmsuBJppsGHg5FoU789aC+5ghFmyblkDij6A2x2l10D9qV6fNfYVtt72O7MM5xahKdnjvBJ5LFmaNeLeIf9hTzhMmZ1eFS1SWt5XsiP/ARJ8Y0G+CeAKSeDwQ2rsZhNcLwujzyV1JbESZgqfWNs5uVJspLP9lpryjfdRW+hipDjVL8QuK8U1MSQgLor3HlwI+a3OOJpv/BrZp455gr5N/J8mDaQ/KUmG68/EXQlqQJvqDTSmSV9MWHqptAMnDKB24YKlj+e4HydQvZM1d6O97ElqaZiLOq83iHzlhfG9XKwUJYIEaQGOWy3M3t0tNpZQoczc3E2MX3zPsIevMlFT+DAUggiw2NlTbZ3RHnA2sc=
