################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonar.klauke-enterprises.com -Dsonar.projectKey=portum -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - secure: fivUa2dCWkeOFp2IoMfPXgKFrlkyTVDYNpLEqsZ9XqyXurrrXXdSr5l9kL8S1HIlnb1X3YKM481r+jbRgo8ugdIcE3D2TygJ5e93rFdzIxDGEokuScOs6YadhfX3uTuMrH5ly60dj8/QCs9wBJvNZGx6vxEE+V9FPby2x8zDULAV3+fQUugqcqEaov8mTrRVqmk3Qv08026NTHKxix7EaAcCRkZhLvGM8LfEDGRGuoZFdkrlkGuqlLQbbO/FwyWlW+C7to8pTe+unSsik9jOKHwMc2kY1u22ShZvSZD0/YD7gGOn1Z80dFVvJ8hwtgOaAWtzCR9xYSfeeirUzPI6A+ErweJocqfco2RabpUtNH9L4zes4nPfhvFNLKzh28Qpch6wbJWpRqP/mNRL7W9JezV2yN5gQt/kZ1Fs0um9FFdzW22CITeBqD8BnJ34wDuuWTuWCfsm9JhArnxtjHUiTzTnC15oXlPMgYT5Fl5aLBWxTZnvG7+b8jzx1zxwoSikA7dMAU5hNTermEVY4mCairZgi1BxamPHhf95j+oteqd6l1xQ/b0oT1z9C91ecT9Bkdc1riEFuOtZe1v66kTjrQhEuNISDdekfB4vnK4xM8CczHceGh6NxDgZhZPW3fZLercJc2KRLq3UsyYLS1pftYXJUrp/eUT1WTjnWr9mM48=
    - secure: l+zM2wrR1Q/kMQoSUhK0WeeZnk2yvJEwqs3taWaOKDJOEay8VzEl1X4LJgHi0ymKThIjLCOrQQY+orB7kMi3ThZlOGTQ7cAPa3+gUCS4yAlhoQrQdTQ1dnSMM36ju0QOTOksSt0ZqVAA3ULIH7DHnbGnss5iHAuiQYgSTDDCa7MPi1YdnqXoN+pGGDu2CF4N6PqHKvPhd6J8O/bsM/9YJ7FCd/yySf5896OF6w5XO3xKuxC7Ib0D6VngtHr+v+1erkwtlhbwqUISn8Ww8KoVwiHU3GBAgpKS0JhNJ9YcUkuHiAUKvvrWL81svWplE07OWytD+KJxqr1VS0NJJVEWi6CYAcngplvLDLXx3qBi8WFZRl2aMBKmUXP/SgV+uTsQ3LCUE+LAj7Zxu51EK31cgiKpjyGxL7fbHOZz9PT5zv8SGpBJzlA7ZIpbwybmCGMmDmEyjV6F9TiSCVI0TdKEBkYFVPTj1ltq2qjwqP7skhp8KV1wirdL7y2hP7ewAG3Qj64d95Y2gYL0AoUDQcc+D62DDiIiBaccJxcvyxWylDlwT0xA+rPC9CuSO+y2+7da/+jaKGYIB6D4lk2dZRk7sCzdifZg3JuzJVBJeAYzPjyAsfH5esHk1inuyjLM2VFbmzqiJ3H253MLjMrotLzoSg7PzLxnMWmKLmhKT9N8UK4=
    - secure: n+JgPBIjK7J2jHB+9hnPvZnCvifCqC2J3Y9JZK7o4jUvtfsYy/8OS304MbzVgmcqwW1/dOZ2Y0ZeyIoURVmMLYoHv7n4VmKVoyGUyICyT321MaT8cjpS1CM5KXGF9t5n0L8SR+bOrVEU+tGnyXleavgojnxxPgV9CxpRIt7oE/Q9k+g7/j7Ylmyoh2Jy3D4Fm2wPfOykyE+AAMOiVMfoDuwtFuXwM6D72W3eB4eduIjquBKql860kpljXyfFOudM2GooZtTCxfZM1Y8mvTCn2Q1mX5C8KxCoIHk3sK/k3w7Bk7jEfAwGPDqGYttj2w4GS+BzZ4Ywv9gj67XzTS7dFXc8oWiFW12+L3hSvX/LCbunbdZY426+FdaYof2KstDRh3rQoxlgEcGkYbSA2j/m3tVPwj/k0hjPTGWHz7F5gIUoDcNqf+G/t1F07IMHUt097DCprVDyXAzQE8jlDE9ylFMOrV3y++58x1gKDv9JYfB9iMXwNOLwaHgOXFLNqg3nP1NgO60ajhLlElVov65wbyvuwaByz0RNISRhclyq//Z0vJT5Mg7i2Qqwybj2uSiPrwVwhs7I7KOIIzgZEcX0tgkPsb7Ai4AkVWxR7F+SCoavEOJdT1eVZal0+9pmx7rZILf94xnMR33gAmaAT9ZJKuVjdJ0NzbvKGGpwZZIKPSI=
